- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update Pacman
      pacman:
        update_cache: yes
        upgrade: yes
      changed_when: False
    - name: Update Apt
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: False
      
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    
