- name: Install packages pacman
  pacman:
    name:
      - htop
      - git
      - ansible
      - vim

- name: Install packages apt
  apt:
    name:
      - htop
      - git
      - ansible
      - vim

