- name: Install packages pacman
  pacman:
    name:
      - htop
      - git
      - ansible
      - vim
  when: ansible_facts['distribution'] == 'Manjaro'

- name: Install packages apt
  apt:
    name:
      - htop
      - git
      - ansible
      - vim
  when: ansible_facts['distribution'] == 'Ubuntu'

